name: Time to Bake...

on: 
  #releasepush:
    #pushbuild

  watch: 
      types: [started]
    
env:              #change ROM_URL,ROM_NAME,ZIP_NAME,ROMZIP_NAME respectivley. ROM_NAME is case sensitive 
  ROM_URL: https://iweb.dl.sourceforge.net/project/rmx1851/OxygenOS_sGSI_RMX1851/oxygenOS_OP7T_OOS10_sGSI_RMX1851_Zaxceed.zip
  ROM_NAME: Generic:Oxygenport
  ROMZIP_NAME: oxygenOS_OP7T_OOS10_sGSI_RMX1851_Zaxceed.zip
  ZIP_NAME: oosportpb-HELIOS-07-10
  SECRETS_PASSWORD: ${{ secrets.SFGPASS }}
  SECRETS_GITPASS: ${{ secrets.GIT }}
  SECRETS_REPOS: ${{ secrets.REPOS }}
  SECRETS_USERG: ${{ secrets.USERG }}
  SECRETS_USERP: ${{ secrets.USERP }}
  TZ: Middle-East/Kuwait
  SFDIRA1: cd /home/pfs/project/helios-gsis/HeliosBakery
  SFDIRA2: cd /home/pfs/project/helios-gsis/Heliosbakerybills
  SFUSER: ${{ secrets.SFUSER }}
  
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
       - name: Checkout
         uses: actions/checkout@main
       
           
       - name: Setting up the SPICES and its SPICES
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
            sudo -E apt-get -qq install python3
            sudo -E apt-get -qq install simg2img
            sudo apt-get install -y expect
            
       - name: test setup 
         run:  |
           expect -c " 
           spawn git clone ${{ secrets.REPOS }} ErfanGSIs
           expect \"Username or email address\"        
           send \"$SECRETS_USERG\r\"
           expect \"Password\"        
           send \"$SECRETS_USERP\r\"
           set timeout -1
           catch wait result
           interact"
       
       - name: DOWNLOADING THE FIRMWARE
         run: cd ErfanGSIs && sudo bash setup.sh && sudo wget $ROM_URL 
       
       - name: GENERATION OF BAKED GOODIES
         run: 
            |
            cd ErfanGSIs && sudo ./gsi.sh $ROMZIP_NAME $ROM_NAME
            
             
       - name: Zipping BOTH COOKIES
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z ErfanGSIs/output/*-Aonly-*.img 
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z ErfanGSIs/output/*-AB-*.img
              
       - name: uploading to HELIOSBAKERY
         run: |   
              cd ErfanGSIs/output
              expect -c " 
              spawn sftp $SFUSER
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFGPASS }}\r\"
              expect \"sftp> \"
              send \"$SFDIRA2\r\"
              set timeout -1
              send \"put *-Aonly-*.txt\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              interact"
              expect -c "
              spawn sftp $SFUSER
              expect \"Password\"
              send \"${{ secrets.SFGPASS }}\r\"
              expect \"sftp> \"
              send \"$SFDIRA1\r\"
              set timeout -1
              send \"put $ZIP_NAME-GSI-Aonly.7z\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              interact"
              expect -c "
              spawn sftp $SFUSER
              expect \"Password\"
              send \"${{ secrets.SFGPASS }}\r\"
              expect \"sftp> \"
              send \"$SFDIRA1\r\"
              set timeout -1
              send \"put $ZIP_NAME-GSI-AB.7z\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"  
                  
